services:
  ms-sql-headquarter:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: ms-sql-headquarter
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=MyStrongPassword123
    ports:
      - "1433:1433"
    volumes:
      - sql-data-hq:/var/opt/mssql
    networks:
      - sb-network
  ms-sql-branch-1:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: ms-sql-branch-1
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=MyStrongPassword123
    ports:
      - "1434:1433"
    volumes:
      - sql-data-branch-1:/var/opt/mssql
    networks:
      - sb-network
  ms-sql-branch-2:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: ms-sql-branch-2
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=MyStrongPassword123
    ports:
      - "1435:1433"
    volumes:
      - sql-data-branch-2:/var/opt/mssql
    networks:
      - sb-network
  ms-sql-credit-card:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: ms-sql-credit-card
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=MyStrongPassword123
    ports:
      - "1436:1433"
    volumes:
      - sql-data-credit-card:/var/opt/mssql
    networks:
      - sb-network
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - sb-network
  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
    networks:
      - sb-network
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - sb-network

networks:
  sb-network:

volumes:
  sql-data-hq:
  sql-data-branch-1:
  sql-data-branch-2:
  sql-data-credit-card: