server:
  port: 8079

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: credit-card-service
  datasource:
    url: jdbc:sqlserver://localhost:1436;databaseName=my_database;encrypt=false
    username: sa
    password: MyStrongPassword123
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    database-platform: org.hibernate.dialect.SQLServerDialect
    hibernate:
      ddl-auto: update
    show-sql: true
