server:
  port: 8070

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:sqlserver://localhost:1437;databaseName=my_database;encrypt=false
    username: sa
    password: MyStrongPassword123
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    database-platform: org.hibernate.dialect.SQLServerDialect
    hibernate:
      ddl-auto: update
    show-sql: true

app:
  jwt:
    key: 7e901df4274b02f77a59b5862c97f43b69924d29feca6feadc61735a91321bd8
    expiration: 86400000